#!/bin/sh
set -eu

umask 077

# Read a secret from VAR_FILE into VAR.  This follows the same convention as
# the official PostgreSQL image while keeping secret values out of `docker
# inspect` and Compose environment blocks.
file_env() {
    var="$1"
    file_var="${var}_FILE"

    eval "value=\${${var}:-}"
    eval "file=\${${file_var}:-}"

    if [ -n "$value" ] && [ -n "$file" ]; then
        echo "error: both ${var} and ${file_var} are set" >&2
        exit 1
    fi

    if [ -n "$file" ]; then
        if [ ! -r "$file" ]; then
            echo "error: secret file is not readable: ${file}" >&2
            exit 1
        fi
        value="$(cat "$file")"
        export "$var=$value"
    fi

    unset "$file_var" || true
}

if [ "${BBW_SKIP_DATABASE_CONFIG:-false}" != "true" ]; then
    # Only the PostgreSQL password must be materialized because SQLAlchemy
    # expects one URL.  All other application secrets stay file-backed.
    file_env POSTGRES_PASSWORD

    # Secrets generated by docker/init-secrets.sh are URL-safe hex.
    if [ -z "${BBW_DATABASE_URL:-}" ]; then
        : "${POSTGRES_HOST:=postgres}"
        : "${POSTGRES_PORT:=5432}"
        : "${POSTGRES_DB:=bbw}"
        : "${POSTGRES_USER:=bbw}"
        : "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD or POSTGRES_PASSWORD_FILE is required}"

        case "$POSTGRES_PASSWORD" in
            *[!A-Za-z0-9._~-]*)
                echo "error: POSTGRES_PASSWORD must be URL-safe; use docker/init-secrets.sh" >&2
                exit 1
                ;;
        esac
        export BBW_DATABASE_URL="postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    fi
    unset POSTGRES_PASSWORD
fi

exec "$@"
