"""Initial production persistence and security schema.

Revision ID: 20260716_0001
Revises: None
Create Date: 2026-07-16
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "20260716_0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('totp_secret_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_totp_counter', sa.BigInteger(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('username', name=op.f('uq_admin_users_username'))
    )
    op.create_index('ix_admin_users_active', 'admin_users', ['is_active'], unique=False)
    op.create_table('system_storage_quota',
    sa.Column('id', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('quota_bytes', sa.BigInteger(), server_default='8589934592', nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_system_storage_quota_system_storage_singleton')),
    sa.CheckConstraint('quota_bytes > 0', name=op.f('ck_system_storage_quota_system_storage_quota_positive')),
    sa.CheckConstraint('used_bytes <= quota_bytes', name=op.f('ck_system_storage_quota_system_storage_within_quota')),
    sa.CheckConstraint('used_bytes >= 0', name=op.f('ck_system_storage_quota_system_storage_used_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_storage_quota'))
    )
    op.create_table('admin_sessions',
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('sid_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sensitive_unlocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=160), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.CheckConstraint('idle_expires_at <= absolute_expires_at', name=op.f('ck_admin_sessions_admin_session_idle_before_absolute')),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_admin_sessions_admin_user_id_admin_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_sessions')),
    sa.UniqueConstraint('sid_hash', name=op.f('uq_admin_sessions_sid_hash'))
    )
    op.create_index('ix_admin_sessions_admin_active', 'admin_sessions', ['admin_user_id', 'revoked_at', 'absolute_expires_at'], unique=False)
    op.create_index(op.f('ix_admin_sessions_admin_user_id'), 'admin_sessions', ['admin_user_id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('max_uses', sa.Integer(), server_default='1', nullable=False),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('max_uses >= 1', name=op.f('ck_invite_codes_invite_max_uses_positive')),
    sa.CheckConstraint('use_count <= max_uses', name=op.f('ck_invite_codes_invite_use_count_within_max')),
    sa.CheckConstraint('use_count >= 0', name=op.f('ck_invite_codes_invite_use_count_nonnegative')),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], name=op.f('fk_invite_codes_created_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_invite_codes_code_hash'))
    )
    op.create_index('ix_invite_codes_available', 'invite_codes', ['disabled_at', 'expires_at'], unique=False)
    op.create_index(op.f('ix_invite_codes_created_by_admin_id'), 'invite_codes', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_invite_codes_expires_at'), 'invite_codes', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('status', sa.String(length=24), server_default='active', nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('invite_code_id', sa.UUID(), nullable=True),
    sa.Column('media_quota_bytes', sa.BigInteger(), server_default='104857600', nullable=False),
    sa.Column('media_used_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('chat_retention_days', sa.SmallInteger(), server_default='180', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('chat_retention_days >= 1', name=op.f('ck_users_user_chat_retention_positive')),
    sa.CheckConstraint('media_quota_bytes > 0', name=op.f('ck_users_user_media_quota_positive')),
    sa.CheckConstraint('media_used_bytes <= media_quota_bytes', name=op.f('ck_users_user_media_within_quota')),
    sa.CheckConstraint('media_used_bytes >= 0', name=op.f('ck_users_user_media_used_nonnegative')),
    sa.ForeignKeyConstraint(['invite_code_id'], ['invite_codes.id'], name=op.f('fk_users_invite_code_id_invite_codes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_invite_code_id'), 'users', ['invite_code_id'], unique=False)
    op.create_index('ix_users_status_created', 'users', ['status', 'created_at'], unique=False)
    op.create_table('activity_events',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), server_default='beibeiwu', nullable=False),
    sa.Column('upstream_event_id', sa.String(length=256), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_upstream_uid', sa.String(length=128), nullable=True),
    sa.Column('subject_upstream_uid', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_activity_events_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_events')),
    sa.UniqueConstraint('owner_user_id', 'provider', 'upstream_event_id', name='uq_activity_events_owner_source')
    )
    op.create_index('ix_activity_events_owner_occurred', 'activity_events', ['owner_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_activity_events_owner_type', 'activity_events', ['owner_user_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_activity_events_owner_user_id'), 'activity_events', ['owner_user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_audit_logs_admin_user_id_admin_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_audit_logs_target_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_admin_created', 'audit_logs', ['admin_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_user_id'), 'audit_logs', ['admin_user_id'], unique=False)
    op.create_index('ix_audit_logs_expiry', 'audit_logs', ['expires_at'], unique=False)
    op.create_index('ix_audit_logs_target_created', 'audit_logs', ['target_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_user_id'), 'audit_logs', ['target_user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), server_default='tim', nullable=False),
    sa.Column('upstream_conversation_id', sa.String(length=256), nullable=False),
    sa.Column('peer_upstream_uid', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=32), server_default='direct', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('unread_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_conversations_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('id', 'owner_user_id', name='uq_conversations_id_owner'),
    sa.UniqueConstraint('owner_user_id', 'provider', 'upstream_conversation_id', name='uq_conversations_owner_source')
    )
    op.create_index('ix_conversations_owner_last_message', 'conversations', ['owner_user_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_owner_user_id'), 'conversations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_peer_upstream_uid'), 'conversations', ['peer_upstream_uid'], unique=False)
    op.create_table('external_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), server_default='beibeiwu', nullable=False),
    sa.Column('upstream_uid', sa.String(length=128), nullable=True),
    sa.Column('phone_hmac', sa.String(length=64), nullable=False),
    sa.Column('phone_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('login_account_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('password_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('last_authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_external_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_accounts')),
    sa.UniqueConstraint('id', 'user_id', name='uq_external_accounts_id_user'),
    sa.UniqueConstraint('provider', 'phone_hmac', name='uq_external_accounts_provider_phone'),
    sa.UniqueConstraint('provider', 'upstream_uid', name='uq_external_accounts_provider_uid'),
    sa.UniqueConstraint('user_id', name='uq_external_accounts_user')
    )
    op.create_index(op.f('ix_external_accounts_user_id'), 'external_accounts', ['user_id'], unique=False)
    op.create_table('operation_outbox',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(length=96), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=True),
    sa.Column('aggregate_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='8', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_operation_outbox_outbox_attempt_nonnegative')),
    sa.CheckConstraint('max_attempts >= 1', name=op.f('ck_operation_outbox_outbox_max_attempt_positive')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_operation_outbox_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_outbox')),
    sa.UniqueConstraint('owner_user_id', 'operation_type', 'idempotency_key', name='uq_outbox_idempotency')
    )
    op.create_index(op.f('ix_operation_outbox_owner_user_id'), 'operation_outbox', ['owner_user_id'], unique=False)
    op.create_index('ix_outbox_claim', 'operation_outbox', ['status', 'available_at', 'locked_until'], unique=False)
    op.create_index('ix_outbox_owner_created', 'operation_outbox', ['owner_user_id', 'created_at'], unique=False)
    op.create_table('raw_upstream_responses',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('request_correlation_id', sa.String(length=128), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('encrypted_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_raw_upstream_responses_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_upstream_responses'))
    )
    op.create_index('ix_raw_upstream_expiry', 'raw_upstream_responses', ['expires_at'], unique=False)
    op.create_index('ix_raw_upstream_owner_received', 'raw_upstream_responses', ['owner_user_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_raw_upstream_responses_owner_user_id'), 'raw_upstream_responses', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_raw_upstream_responses_request_correlation_id'), 'raw_upstream_responses', ['request_correlation_id'], unique=False)
    op.create_table('relationships',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), server_default='beibeiwu', nullable=False),
    sa.Column('subject_upstream_uid', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_relationships_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships')),
    sa.UniqueConstraint('owner_user_id', 'provider', 'subject_upstream_uid', 'kind', name='uq_relationships_owner_subject')
    )
    op.create_index('ix_relationships_owner_kind_status', 'relationships', ['owner_user_id', 'kind', 'status'], unique=False)
    op.create_index(op.f('ix_relationships_owner_user_id'), 'relationships', ['owner_user_id'], unique=False)
    op.create_table('sync_cursors',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('stream', sa.String(length=96), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('watermark_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_sync_cursors_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_cursors')),
    sa.UniqueConstraint('owner_user_id', 'source', 'stream', name='uq_sync_cursors_owner_stream')
    )
    op.create_index('ix_sync_cursors_due', 'sync_cursors', ['next_sync_at', 'last_succeeded_at'], unique=False)
    op.create_index(op.f('ix_sync_cursors_next_sync_at'), 'sync_cursors', ['next_sync_at'], unique=False)
    op.create_index(op.f('ix_sync_cursors_owner_user_id'), 'sync_cursors', ['owner_user_id'], unique=False)
    op.create_table('messages',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), server_default='tim', nullable=False),
    sa.Column('upstream_message_id', sa.String(length=256), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('sender_upstream_uid', sa.String(length=128), nullable=True),
    sa.Column('recipient_upstream_uid', sa.String(length=128), nullable=True),
    sa.Column('message_type', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='received', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id', 'owner_user_id'], ['conversations.id', 'conversations.owner_user_id'], name='fk_messages_conversation_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('id', 'owner_user_id', name='uq_messages_id_owner'),
    sa.UniqueConstraint('owner_user_id', 'provider', 'upstream_message_id', name='uq_messages_owner_source')
    )
    op.create_index('ix_messages_conversation_occurred', 'messages', ['conversation_id', 'occurred_at'], unique=False)
    op.create_index('ix_messages_owner_occurred', 'messages', ['owner_user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_messages_owner_user_id'), 'messages', ['owner_user_id'], unique=False)
    op.create_index('ix_messages_retention', 'messages', ['retention_expires_at'], unique=False)
    op.create_table('web_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('external_account_id', sa.UUID(), nullable=False),
    sa.Column('sid_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=160), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.CheckConstraint('idle_expires_at <= absolute_expires_at', name=op.f('ck_web_sessions_web_session_idle_before_absolute')),
    sa.ForeignKeyConstraint(['external_account_id', 'user_id'], ['external_accounts.id', 'external_accounts.user_id'], name='fk_web_sessions_account_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_sessions')),
    sa.UniqueConstraint('sid_hash', name=op.f('uq_web_sessions_sid_hash'))
    )
    op.create_index('ix_web_sessions_user_active', 'web_sessions', ['user_id', 'revoked_at', 'absolute_expires_at'], unique=False)
    op.create_index(op.f('ix_web_sessions_user_id'), 'web_sessions', ['user_id'], unique=False)
    op.create_table('media_objects',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('r2_bucket', sa.String(length=128), nullable=False),
    sa.Column('r2_object_key', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('counts_toward_quota', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_media_objects_media_size_nonnegative')),
    sa.ForeignKeyConstraint(['message_id', 'owner_user_id'], ['messages.id', 'messages.owner_user_id'], name='fk_media_objects_message_owner', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_media_objects_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_objects')),
    sa.UniqueConstraint('r2_bucket', 'r2_object_key', name='uq_media_objects_r2_object')
    )
    op.create_index(op.f('ix_media_objects_message_id'), 'media_objects', ['message_id'], unique=False)
    op.create_index('ix_media_objects_owner_status', 'media_objects', ['owner_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_media_objects_owner_user_id'), 'media_objects', ['owner_user_id'], unique=False)
    op.create_index('ix_media_objects_retention', 'media_objects', ['retention_expires_at'], unique=False)
    op.create_index(op.f('ix_media_objects_sha256'), 'media_objects', ['sha256'], unique=False)
    # ### end Alembic commands ###

    op.execute(
        "INSERT INTO system_storage_quota (id, quota_bytes, used_bytes, version) "
        "VALUES (1, 8589934592, 0, 1) ON CONFLICT (id) DO NOTHING"
    )
    op.execute(
        """
        CREATE FUNCTION bbw_protect_audit_log_row() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'UPDATE' THEN
                RAISE EXCEPTION 'audit logs are immutable';
            END IF;
            IF TG_OP = 'DELETE' AND OLD.expires_at > CURRENT_TIMESTAMP THEN
                RAISE EXCEPTION 'audit log retention period has not elapsed';
            END IF;
            RETURN OLD;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER trg_audit_logs_immutable BEFORE UPDATE OR DELETE ON audit_logs "
        "FOR EACH ROW EXECUTE FUNCTION bbw_protect_audit_log_row()"
    )
    op.execute(
        """
        CREATE FUNCTION bbw_reject_audit_log_truncate() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit logs cannot be truncated';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER trg_audit_logs_no_truncate BEFORE TRUNCATE ON audit_logs "
        "FOR EACH STATEMENT EXECUTE FUNCTION bbw_reject_audit_log_truncate()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_truncate ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS bbw_reject_audit_log_truncate()")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_immutable ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS bbw_protect_audit_log_row()")
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_objects_sha256'), table_name='media_objects')
    op.drop_index('ix_media_objects_retention', table_name='media_objects')
    op.drop_index(op.f('ix_media_objects_owner_user_id'), table_name='media_objects')
    op.drop_index('ix_media_objects_owner_status', table_name='media_objects')
    op.drop_index(op.f('ix_media_objects_message_id'), table_name='media_objects')
    op.drop_table('media_objects')
    op.drop_index(op.f('ix_web_sessions_user_id'), table_name='web_sessions')
    op.drop_index('ix_web_sessions_user_active', table_name='web_sessions')
    op.drop_table('web_sessions')
    op.drop_index('ix_messages_retention', table_name='messages')
    op.drop_index(op.f('ix_messages_owner_user_id'), table_name='messages')
    op.drop_index('ix_messages_owner_occurred', table_name='messages')
    op.drop_index('ix_messages_conversation_occurred', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_sync_cursors_owner_user_id'), table_name='sync_cursors')
    op.drop_index(op.f('ix_sync_cursors_next_sync_at'), table_name='sync_cursors')
    op.drop_index('ix_sync_cursors_due', table_name='sync_cursors')
    op.drop_table('sync_cursors')
    op.drop_index(op.f('ix_relationships_owner_user_id'), table_name='relationships')
    op.drop_index('ix_relationships_owner_kind_status', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_raw_upstream_responses_request_correlation_id'), table_name='raw_upstream_responses')
    op.drop_index(op.f('ix_raw_upstream_responses_owner_user_id'), table_name='raw_upstream_responses')
    op.drop_index('ix_raw_upstream_owner_received', table_name='raw_upstream_responses')
    op.drop_index('ix_raw_upstream_expiry', table_name='raw_upstream_responses')
    op.drop_table('raw_upstream_responses')
    op.drop_index('ix_outbox_owner_created', table_name='operation_outbox')
    op.drop_index('ix_outbox_claim', table_name='operation_outbox')
    op.drop_index(op.f('ix_operation_outbox_owner_user_id'), table_name='operation_outbox')
    op.drop_table('operation_outbox')
    op.drop_index(op.f('ix_external_accounts_user_id'), table_name='external_accounts')
    op.drop_table('external_accounts')
    op.drop_index(op.f('ix_conversations_peer_upstream_uid'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_owner_user_id'), table_name='conversations')
    op.drop_index('ix_conversations_owner_last_message', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_target_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_target_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_expiry', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_admin_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_activity_events_owner_user_id'), table_name='activity_events')
    op.drop_index('ix_activity_events_owner_type', table_name='activity_events')
    op.drop_index('ix_activity_events_owner_occurred', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_users_status_created', table_name='users')
    op.drop_index(op.f('ix_users_invite_code_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_invite_codes_expires_at'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_created_by_admin_id'), table_name='invite_codes')
    op.drop_index('ix_invite_codes_available', table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_admin_sessions_admin_user_id'), table_name='admin_sessions')
    op.drop_index('ix_admin_sessions_admin_active', table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_table('system_storage_quota')
    op.drop_index('ix_admin_users_active', table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
